# Built with Jekyll 3.2.0

# Setup
title:               Thodi on trading
tagline:             'the making of a trader'
description:         'I share my experiences, lessons and knowledge I acquire on my journey into the world of financial trading and investing.'
url:                 'http://minicomp.github.io'
baseurl:             '/thodi'

# About/contact
author:
  name:              Martin Thodi
  url:               https://creator.miyanda.org
  email:             martthodi238[at]gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
